name: "Question"
description: "Spurning eða álitamál sem hópurinn vill ræða"
title: "[SPURNING] Stutt lýsing"
labels:
  - question
body:
  - type: textarea
    id: context
    attributes:
      label: "Um hvað snýst spurningin?"
      description: "Lýsið stuttlega því sem hópurinn er að velta fyrir sér."
      placeholder: "Hvað eigum við að gera ef..."
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: "Hvað höfum við prófað eða hugsað?"
      description: "Segið frá því sem þið hafið prófað eða rætt áður en þið spurðuð."
      placeholder: "Við prófuðum að..."
    validations:
      required: false

