name: Heuristic Evaluation Issue
description: Skra usability-vandamal skv. Nielsen heuristics
title: "[HEURISTIC] Stutt lýsing"
labels:
  - usability
  - heuristic

body:
  - type: dropdown
    id: heuristic
    attributes:
      label: Hvaða heuristic a þetta vid?
      options:
        - Visibility & Feedback
        - Match to real world
        - User control & error prevention
        - Consistency & standards
        - Recognition over recall
        - Flexibility & efficiency
        - Aesthetics & minimalism
      description: Veldu flokk sem a best vid.
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Alvarleiki
      options:
        - severity:1 - minor
        - severity:2 - low
        - severity:3 - medium
        - severity:4 - high
        - severity:5 - critical
      description: Veldu alvarleika.
    validations:
      required: true

  - type: input
    id: linked_task
    attributes:
      label: Tengt task (nr ur TASKS.md)
      placeholder: "1"
      description: Sladu inn task-numer sem tengist þessu issue.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Samhengi / task og sidur
      placeholder: 'Daemi: "Leita ad voru og setja i korfu" a /search og /product'
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Skref til ad endurskapa
      placeholder: "1) Opna /search  2) Sladu inn ...  3) ..."
    validations:
      required: true

  - type: textarea
    id: observed
    attributes:
      label: Raunverd hegðun (observed)
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Aeskileg hegðun (expected)
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Tillaga ad urbót (optional)
      placeholder: Stutt lausn eða hugmynd að betrumbót.
    validations:
      required: false

  - type: checkboxes
    id: evidence
    attributes:
      label: Sonnunargogn (optional)
      options:
        - label: Skjamynd eða video fylgir (draga & sleppa nedan)

